=== DerFreundlichste/DB_Prak3/rechnung.dtd
<!ELEMENT RECH (RENR, RDAT, KNR, KNAME, PLZ, ORT, Strasse, ARTNR, ARTBEZ, BMENGE, ERBET)>
<!ELEMENT RENR (#PCDATA)>
<!ELEMENT RDAT (#PCDATA)>
<!ELEMENT KNR (#PCDATA)>
<!ELEMENT KNAME (#PCDATA)>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT ORT (#PCDATA)>
<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT ARTNR (#PCDATA)>
<!ELEMENT ARTBEZ (#PCDATA)>
<!ELEMENT BMENGE (#PCDATA)>
<!ELEMENT ERBET (#PCDATA)>

=== DerFreundlichste/DB_Prak3/RECH-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECH SYSTEM "rechnung.dtd">
<RECH>
	<RENR>8R</RENR>
	<RDAT>2017-12-29 00:00:00</RDAT>
	<KNR>1</KNR>
	<KNAME>Hans MÃ¼ller</KNAME>
	<PLZ>33575</PLZ>
	<ORT>Buschhausen</ORT>
	<Strasse>Baumallee</Strasse>
	<ARTNR>0</ARTNR>
	<ARTBEZ>H-Milch</ARTBEZ>
	<BMENGE>0</BMENGE>
	<ERBET>0.00</ERBET>
</RECH>
